stages:
  - mirror

mirror_to_github:
  stage: mirror
  image: alpine:latest

  before_script:
    - apk add --no-cache git openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan github.com >> ~/.ssh/known_hosts

  script:
    - git config --global user.email "you@example.com"
    - git config --global user.name "GitLab Mirror"

    - git remote add github git@github.com:Abhinav2231989/MedicalVault.git || true

    - git push github --all
    - git push github --tags

  only:
    - main